version = 1

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "kotlin"

  [analyzers.meta]
  runtime_version = "1.8"
  language_version = "1.7"

[[analyzers]]
name = "swift"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "angularjs",
    "meteor",
    "ember",
    "react",
    "vue",
    "angular"
  ]
  environment = [
    "vitest",
    "cypress",
    "mongo",
    "jquery",
    "nodejs",
    "browser",
    "jest",
    "mocha",
    "jasmine"
  ]

[[analyzers]]
name = "cxx"

[[code_formatters]]
name = "clang-format"

[[code_formatters]]
name = "prettier"

[[code_formatters]]
name = "standardjs"

[[code_formatters]]
name = "swift-format"

[[code_formatters]]
name = "ktlint"