version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "vue"
  ]
  environment = [
    "vitest",
    "nodejs"
  ]

[[analyzers]]
name = "python"
dependency_file_paths = [
  "requirements/requirements_project.txt"
]

  [analyzers.meta]
  max_line_length = 100


[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"

[[analyzers]]
name = "swift"

[[code_formatters]]
name = "swift-format"

[[code_formatters]]
name = "rustfmt"

[[code_formatters]]
name = "black"

[[code_formatters]]
name = "prettier"