version = 1

test_patterns = ["tests/**, **/test_*.py"]

exclude_patterns = ["venv/**"]

[[analyzers]]
name = "kotlin"

  [analyzers.meta]
  runtime_version = "1.8"
  language_version = "1.7"

[[analyzers]]
name = "cxx"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "vue",
    "angularjs",
    "meteor",
    "ember",
    "angular"
  ]
  environment = [
    "vitest",
    "nodejs",
    "browser",
    "mongo",
    "jquery",
    "jest",
    "cypress",
    "mocha",
    "jasmine"
  ]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"

[[analyzers]]
name = "swift"

[[code_formatters]]
name = "swift-format"

[[code_formatters]]
name = "rustfmt"

[[code_formatters]]
name = "black"

[[code_formatters]]
name = "prettier"

[[code_formatters]]
name = "ruff"

[[code_formatters]]
name = "autopep8"

[[code_formatters]]
name = "yapf"

[[code_formatters]]
name = "isort"

[[code_formatters]]
name = "standardjs"

[[code_formatters]]
name = "clang-format"

[[code_formatters]]
name = "ktlint"